name: in_a_hat
description: "A project to make a simple quiz game."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  freezed: ^2.4.7
  dio: ^5.4.1
  auto_route: ^7.8.4
  freezed_annotation: ^2.4.1

  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4

  uuid: ^4.3.3
  flutter_svg: ^2.0.10+1

  injectable: ^2.3.2
  get_it: ^7.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  injectable_generator: ^2.4.1
  auto_route_generator: ^7.3.2
  freezed: ^2.4.7
  riverpod_generator: ^2.3.11
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true
